repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven
        args: ['-f spring-boot-example/pom.xml spotless:apply']
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven
        args: ['-f jakarta-ee-example/pom.xml spotless:apply']
