services:
  database:
    image: postgres:17
    environment:
      - POSTGRES_USER=testcontainers
      - POSTGRES_PASSWORD=secret
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command: [ 'start-dev --http-relative-path /auth' ]
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
