version: "3.8"
services:
  database:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=springboot
      - POSTGRES_PASSWORD=springboot
  localstack:
    image: localstack/localstack:2.0.0
    ports:
      - "4566:4566"
    volumes:
      - type: bind
        source: ./src/test/resources/localstack/init-thumbnail-processing.sh
        target: /docker-entrypoint-initaws.d/init-thumbnail-processing.sh
        read_only: true
