version: '3'
services:
  database:
    image: postgres:17
    environment:
      - POSTGRES_USER=testcontainers
      - POSTGRES_PASSWORD=secret
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KEYCLOAK_DB=dev-file
