version: "3.8"
services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=springboot
      - POSTGRES_PASSWORD=springboot
  localstack:
    image: localstack/localstack:4.0.1
    ports:
      - "4566:4566"
    volumes:
      - type: bind
        source: ./src/test/resources/localstack/init-thumbnail-processing.sh
        target: /docker-entrypoint-initaws.d/init-thumbnail-processing.sh
        read_only: true
    environment:
      - SERVICES=s3,sqs
