version: '3'
services:
  database:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=testcontainers
      - POSTGRES_PASSWORD=secret
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    environment:
      - KEYCLOAK_USER=testcontainers
      - KEYCLOAK_PASSWORD=secret
      - DB_VENDOR=h2
